import { aesEncrypt } from "./aesEncrypt";
import { readImage } from "./readImage";

let data = {
    verificationCode: "",
    mobileCountry: "66",
    mobileNo: "880374870",
    email: "dheerapat.t@socket9.com",
    citizenId: "U2FsdGVkX1/VNl5NiAeLzKzf+LvafM8Udz8YwCeqHHc=",
    laserId: aesEncrypt(""),
    idCardExpiryDate: "",
    idCardImage: readImage("dheeto_id.jpg"),
    title: "",
    gender: "",
    firstNameEN: "",
    lastNameEN: "",
    firstNameLocal: "",
    lastNameLocal: "",
    dateOfBirth: "",
    customerImage: readImage("dheeto.jpg"),
    address: {
        address1: "",
        address2: null,
        countryId: "",
        state: null,
        PostalCode: "",
        addressDefine1: null,
        addressDefine2: null,
        stateId: "",
        districtId: "",
        district: "",
        subdistrictId: "",
        subdistrict: ""
    },
    mailingAddress: {
        address1: "",
        address2: null,
        countryId: "",
        state: null,
        PostalCode: "",
        addressDefine1: null,
        addressDefine2: null,
        stateId: "",
        districtId: "",
        district: "",
        subdistrictId: "",
        subdistrict: ""
    },
    occupationId: "",
    occupation: "",
    workPlace: "",
    businessTypeId: "",
    workAddress: {
        address1: "",
        address2: null,
        countryId: "",
        state: null,
        PostalCode: "",
        addressDefine1: null,
        addressDefine2: null,
        stateId: "",
        districtId: "",
        district: "",
        subdistrictId: "",
        subdistrict: ""
    },
    userDefined1: null,
    userDefined2: null,
    userDefined3: null,
    userDefined4: null,
    userDefined5: null,
    userDefined6: null,
    userDefined7: null,
    userDefined8: null,
    userDefined9: null,
    userDefined10: null,
    languageCode: "",
    walletPurposeId: "",
    walletPurposeText: "",
    consentList: [
        {
            consentId: "",
            acceptFlag: true,
            userDefined1: null,
            userDefined2: null,
            consentType: "",
            consentDate: ""
        },
        {
            consentId: "",
            acceptFlag: true,
            userDefined1: null,
            userDefined2: null,
            consentType: "",
            consentDate: ""
        }
    ],
    externalId: "",
    enableManualApproval: false
};